using Domain.Entities;

namespace Domain.Interfaces
{
    public interface IOrderService
    {
        Task<bool> AddOrderAsync(Order order,IEnumerable<OrderItem> items);
        Task<IEnumerable<Order>> GetAllOrdersAsync();
        Task<Order> GetOrderByIdAsync(string orderId);
        Task<Order> GetOrderByOrderNumberAsync(string orderNumber);
        Task<string> AutoGeneratedOrderNumber();
    }
}
